services:
  - type: web
    name: husky-reads-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: husky-reads-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "https://husky-reads-frontend.onrender.com"

  - type: web
    name: husky-reads-frontend
    runtime: docker
    dockerfilePath: ./husky-reads/Dockerfile
    dockerContext: ./husky-reads
    envVars:
      - key: PORT
        value: "80"
      - key: VITE_API_URL
        value: "https://husky-reads-backend.onrender.com"
    dockerBuildArgs:
      - key: VITE_API_URL
        value: "https://husky-reads-backend.onrender.com"

databases:
  - name: husky-reads-db
    plan: free
    databaseName: huskyreads
